title: "HUMANIRE"
description: "HUMAN-centered design and ergonomics for Industrial REconfigurable systems"
url: ""
baseurl: "/humanire"
repository: "gaarbelaez/humanire"
lang: "en"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages:
  - project.md
  - consortium.md
  - work-packages.md
  - news.md
  - publications.md
  - contact.md
